site_name: Valheim Discord Connector
repo_url: https://github.com/nwesterhausen/valheim-discordconnector
theme:
  name: "material"
  locale: "en"
docs_dir: docs
site_dir: bin/mkdocs
strict: true

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - abbr
  - attr_list
  - def_list
  - footnotes
  - codehilite

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - codeinclude
  - markdownextradata
  - img2fig
  - mermaid2
  - navtitles
  - mkdocs_safe_text

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js