site_name: Valheim Discord Connector
repo_url: https://github.com/nwesterhausen/valheim-discordconnector
theme:
  name: "material"
  locale: "en"
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  features:
    - navigation.sections
docs_dir: docs
site_dir: bin/mkdocs
strict: true

nav:
  - index.md
  - changelog.md
  - Installation:
    - webhook-instructions.md
  - Configuration:
    - editing-configuration.md
    - randomized-messages.md
    - configuration-details.md
  - API:
    - bot-commands.md

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - abbr
  - attr_list
  - def_list
  - footnotes
  - codehilite

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - img2fig
  - navtitles

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js