attrs==21.2.0
Babel==2.9.1
beautifulsoup4==4.10.0
bleach==4.1.0
bleach-allowlist==1.0.3
bracex==2.1.1
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
colorama==0.4.4
EditorConfig==0.12.3
ghp-import==2.0.2
gitdb==4.0.7
GitPython==3.1.24
idna==3.2
importlib-metadata==4.8.1
ipython-genutils==0.2.0
Jinja2==3.0.2
jsbeautifier==1.14.0
jsonschema==4.1.0
jupyter-core==4.8.1
Markdown==3.3.4
MarkupSafe==2.0.1
mergedeep==1.3.4
mkdocs==1.2.2
mkdocs-awesome-pages-plugin==2.5.0
mkdocs-blog-plugin==0.25
mkdocs-codeinclude-plugin==0.2.0
mkdocs-git-authors-plugin==0.6
mkdocs-git-revision-date-localized-plugin==0.10.0
mkdocs-img2fig-plugin==0.9.3
mkdocs-markdownextradata-plugin==0.2.4
mkdocs-material==7.3.3
mkdocs-material-extensions==1.0.3
mkdocs-mermaid2-plugin==0.5.2
mkdocs-navtitles==0.1.0
mkdocs-redirects==1.0.3
mkdocs-safe-text-plugin==1.3.1
nbformat==5.1.3
packaging==21.0
pigar==0.10.0
Pygments==2.10.0
pymdown-extensions==9.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
pywin32==302
PyYAML==5.4.1
pyyaml_env_tag==0.1
requests==2.26.0
six==1.16.0
smmap==4.0.0
soupsieve==2.2.1
tags-macros-plugin==0.3.0
traitlets==5.1.0
urllib3==1.26.7
watchdog==2.1.6
wcmatch==8.2
webencodings==0.5.1
zipp==3.6.0
