name: "Upload Docs to Azure Blob Storage"
on: 
  push: 
    branches: 
      - main
      - feature/documentation-site

jobs: 
  Build-Publish_Documentation: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      # Build
      - uses: Tiryoh/actions-mkdocs@v0.8.0
      # Upload
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with: 
          container_name: $web
          extra_args: "--destination-path discordconnector.valheim.nwest.games/"
          sas_token: "${{ secrets.AZURE_SAS_TOKEN }}"
          account_name: "${{ secrets.AZURE_ACCOUNT_NAME }}"
          source_dir: bin/mkdocs
          sync: true

